server.port=8883

# 日志等级
logging.level.root=INFO
logging.level.cn.wildfirechat=DEBUG
logging.level.cn.wildfirechat.sdk=DEBUG
logging.level.dev.onvoid.webrtc=DEBUG
# 请求分发与404的调试日志
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.PageNotFound=DEBUG