server.port=8883

#turn server address
ice.url=turn:turn.wildfirechat.net:3478
ice.username=wfchat
ice.password=wfchat1

#video file path
video.file.path=./config/foreman.mp4

#是否只发送音视频，不接收对方的音视频流（仅对高级版音视频有效），true为只发不收
call.send.only=false
#是否定期抓取对端视频截屏保存为bmp文件到运行目录（调试用，长时间运行会产生大量磁盘文件）
video.snapshot.enabled=true
