# 机器人列表，支持配置多个，每个机器人需要独立的ID和secret
# 注意端口是80端口，不是admin的18080端口
# 注意secret是机器人的secret，不是admin的secret
# IM服务器上每个机器人的回调地址都配置为（所有机器人使用同一个地址，服务按消息中的toRobotId自动分发）：
# http://本服务地址:8883/robot/recvmsg
# 会议事件回调地址为：
# http://本服务地址:8883/robot/recvmsg/conference
robots.list[0].im_id=FireRobot
robots.list[0].im_url=http://localhost
robots.list[0].im_secret=123456
#robots.list[1].im_id=FireRobot2
#robots.list[1].im_url=http://localhost
#robots.list[1].im_secret=123456
